default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV['nytimes_database_username'] %>
  password: <%= ENV['nytimes_database_password'] %>

development:
  <<: *default
  host: <%= ENV['nytimes_database_host'] %>
  database: <%= ENV['nytimes_database_name'] %>

test:
  <<: *default
  database: nytimes_test

staging:
  host: <%= ENV['nytimes_database_host'] %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  database: <%= ENV['nytimes_database_name'] %>
  username: <%= ENV['nytimes_database_username'] %>
  password: <%= ENV['nytimes_database_password'] %>

production:
  host: <%= ENV['nytimes_database_host'] %>
  pool: 5
  port: 5432
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['nytimes_database_name'] %>
  username: <%= ENV['nytimes_database_username'] %>
  password: <%= ENV['nytimes_database_password'] %>
